package com.thorium.sdk.hardware;

import oshi.hardware.CentralProcessor;
import oshi.hardware.HardwareAbstractionLayer;
import oshi.software.os.OperatingSystem;
import oshi.util.Util;

import java.io.Serializable;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.UUID;

/**
 * HardwareFingerprint - Generates unique machine identifiers for node-locked licensing.
 *
 * This utility extracts hardware information (CPU ID and Motherboard Serial Number)
 * and generates a unique Hardware ID (HWID) using SHA-256 hashing.
 *
 * Usage:
 *   String hwid = HardwareFingerprint.generateHWID();
 *
 * @author Thorium Team
 * @version 1.0.0
 */
public class HardwareFingerprint implements Serializable {

    private static final long serialVersionUID = 1L;

    // Cache for the generated HWID to avoid repeated hardware queries
    private static String cachedHWID = null;

    /**
     * Generates a unique Hardware ID (HWID) for the current machine.
     *
     * The HWID is generated by:
     * 1. Extracting CPU ID (processor ID)
     * 2. Extracting Motherboard Serial Number
     * 3. Combining them and hashing with SHA-256
     * 4. Taking a portion of the hash as the final HWID
     *
     * @return A unique 16-character HWID string
     */
    public static String generateHWID() {
        if (cachedHWID != null && !cachedHWID.isEmpty()) {
            return cachedHWID;
        }

        String hwid = generateHWIDInternal();
        cachedHWID = hwid;
        return hwid;
    }

    /**
     * Internal method to generate the HWID.
     */
    private static String generateHWIDInternal() {
        String cpuId = getCpuId();
        String motherboardSerial = getMotherboardSerial();
        String macAddress = getMacAddress();

        // Combine available hardware identifiers
        String combined = combineIdentifiers(cpuId, motherboardSerial, macAddress);

        // Hash the combined string
        String hashed = hashSHA256(combined);

        // Return first 16 characters of the hash
        return hashed.substring(0, 16).toUpperCase();
    }

    /**
     * Gets the CPU ID (Processor ID) from the system.
     *
     * @return CPU ID string, or empty string if unavailable
     */
    public static String getCpuId() {
        try {
            oshi.SystemInfo systemInfo = new oshi.SystemInfo();
            HardwareAbstractionLayer hal = systemInfo.getHardware();
            CentralProcessor processor = hal.getProcessor();

            // Get processor ID (varies by OS)
            String processorId = processor.getProcessorID();

            if (processorId != null && !processorId.isEmpty()) {
                // Clean the processor ID - remove special characters
                return processorId.replaceAll("[^A-Za-z0-9]", "").substring(0,
                    Math.min(16, processorId.replaceAll("[^A-Za-z0-9]", "").length()));
            }
        } catch (Exception e) {
            // Fallback: use vendor and processor identifier
            try {
                oshi.SystemInfo systemInfo = new oshi.SystemInfo();
                String vendor = systemInfo.getHardware().getProcessor().getVendor();
                String identifier = systemInfo.getHardware().getProcessor().getIdentifier();
                if (vendor != null && identifier != null) {
                    return (vendor + identifier).hashCode() + "";
                }
            } catch (Exception ex) {
                // Ignore and return empty
            }
        }
        return "";
    }

    /**
     * Gets the Motherboard Serial Number from the system.
     *
     * @return Motherboard serial number, or empty string if unavailable
     */
    public static String getMotherboardSerial() {
        try {
            oshi.SystemInfo systemInfo = new oshi.SystemInfo();
            String serial = systemInfo.getHardware().getComputerSystem().getSerialNumber();

            if (serial != null && !serial.isEmpty() && !serial.equals("Default String")) {
                return serial.replaceAll("[^A-Za-z0-9]", "");
            }
        } catch (Exception e) {
            // Ignore and return empty
        }
        return "";
    }

    /**
     * Gets the Primary MAC Address as a fallback identifier.
     *
     * @return MAC address without colons, or empty string if unavailable
     */
    public static String getMacAddress() {
        try {
            oshi.SystemInfo systemInfo = new oshi.SystemInfo();
            var networkIFs = systemInfo.getHardware().getNetworkIFs();

            if (networkIFs != null && !networkIFs.isEmpty()) {
                // Get first non-loopback interface
                for (var net : networkIFs) {
                    String mac = net.getMACAddress();
                    if (mac != null && !mac.isEmpty() && !mac.equals("00:00:00:00:00:00")) {
                        return mac.replaceAll("[^A-Za-z0-9]", "");
                    }
                }
            }
        } catch (Exception e) {
            // Ignore and return empty
        }
        return "";
    }

    /**
     * Combines available hardware identifiers into a single string.
     * Handles cases where some identifiers are unavailable.
     *
     * @param cpuId CPU ID
     * @param motherboardSerial Motherboard serial number
     * @param macAddress MAC address
     * @return Combined identifier string
     */
    private static String combineIdentifiers(String cpuId, String motherboardSerial, String macAddress) {
        StringBuilder combined = new StringBuilder();

        // Add available identifiers
        if (cpuId != null && !cpuId.isEmpty()) {
            combined.append("CPU:").append(cpuId).append(";");
        }

        if (motherboardSerial != null && !motherboardSerial.isEmpty()) {
            combined.append("MB:").append(motherboardSerial).append(";");
        }

        if (macAddress != null && !macAddress.isEmpty()) {
            combined.append("MAC:").append(macAddress).append(";");
        }

        // If no identifiers available, use UUID based on machine characteristics
        if (combined.length() == 0) {
            combined.append("FALLBACK:").append(UUID.randomUUID().toString());
        }

        return combined.toString();
    }

    /**
     * Hashes a string using SHA-256 algorithm.
     *
     * @param input String to hash
     * @return Hex-encoded SHA-256 hash
     */
    private static String hashSHA256(String input) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(input.getBytes(StandardCharsets.UTF_8));

            StringBuilder hexString = new StringBuilder();
            for (byte b : hash) {
                String hex = Integer.toHexString(0xff & b);
                if (hex.length() == 1) {
                    hexString.append('0');
                }
                hexString.append(hex);
            }

            return hexString.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException("SHA-256 algorithm not available", e);
        }
    }

    /**
     * Gets a shortened version of the HWID (first 4 characters).
     * Used in license key generation.
     *
     * @return First 4 characters of the HWID
     */
    public static String getHWIDPrefix() {
        String hwid = generateHWID();
        return hwid.substring(0, 4);
    }

    /**
     * Clears the cached HWID.
     * Useful for testing or when hardware changes.
     */
    public static void clearCache() {
        cachedHWID = null;
    }

    /**
     * Validates if a given string is a valid HWID format.
     *
     * @param hwid potential HWID to validate
     * @return true if valid HWID format (16 alphanumeric characters)
     */
    public static boolean isValidHWID(String hwid) {
        if (hwid == null || hwid.length() != 16) {
            return false;
        }
        return hwid.matches("^[A-Za-z0-9]{16}$");
    }

    /**
     * Gets detailed hardware information for debugging.
     *
     * @return String containing hardware details
     */
    public static String getHardwareDetails() {
        StringBuilder details = new StringBuilder();

        details.append("=== Hardware Fingerprint Details ===\n");
        details.append("HWID: ").append(generateHWID()).append("\n");
        details.append("CPU ID: ").append(getCpuId()).append("\n");
        details.append("Motherboard Serial: ").append(getMotherboardSerial()).append("\n");
        details.append("MAC Address: ").append(getMacAddress()).append("\n");

        try {
            oshi.SystemInfo systemInfo = new oshi.SystemInfo();
            details.append("\n=== System Information ===\n");
            details.append("Operating System: ").append(systemInfo.getOperatingSystem()).append("\n");
            details.append("Processor: ").append(systemInfo.getHardware().getProcessor()).append("\n");
            details.append("Memory: ").append(systemInfo.getHardware().getMemory()).append("\n");
        } catch (Exception e) {
            details.append("\nError getting system info: ").append(e.getMessage());
        }

        return details.toString();
    }
}
